package digest

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// heatmapDays is the window the activity grid covers: four full weeks.
const heatmapDays = 28

type ActivityItem struct {
	Time    time.Time
	Summary string
	Project string
	Kind    string
}

type DayActivity struct {
	Date  string
	Count int
}

type DigestReport struct {
	Generated   time.Time
	Days        int
	Items       []ActivityItem
	CurrentTask string
	Project     string
	Branch      string
	Heatmap     []DayActivity
	Streak      int
}

// Collect reads one store (inbox, decisions, now.md) and reports the activity
// of the last `days` calendar days plus a four-week heatmap of everything.
func Collect(storeRoot, projectName, branch string, days int) (DigestReport, error) {
	if days < 1 {
		days = 1
	}
	now := time.Now()
	// Calendar days, not a rolling 24h window, so "Today" / "This week" mean
	// what the labels say.
	cutoff := time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, now.Location()).AddDate(0, 0, -(days - 1))

	counts := make(map[string]int)
	var items []ActivityItem
	record := func(item ActivityItem) {
		counts[item.Time.Format("2006-01-02")]++
		if !item.Time.Before(cutoff) {
			items = append(items, item)
		}
	}

	for _, path := range markdownFiles(filepath.Join(storeRoot, "inbox")) {
		for _, item := range parseInboxFile(path, projectName) {
			record(item)
		}
	}
	for _, path := range markdownFiles(filepath.Join(storeRoot, "decisions")) {
		if item, ok := parseDecisionFile(path, projectName); ok {
			record(item)
		}
	}

	sort.Slice(items, func(i, j int) bool { return items[i].Time.After(items[j].Time) })

	report := DigestReport{
		Generated:   now,
		Days:        days,
		Items:       items,
		CurrentTask: parseNowFile(filepath.Join(storeRoot, "now.md")),
		Project:     projectName,
		Branch:      branch,
		Streak:      calculateStreak(counts, now),
	}
	for i := heatmapDays - 1; i >= 0; i-- {
		date := now.AddDate(0, 0, -i).Format("2006-01-02")
		report.Heatmap = append(report.Heatmap, DayActivity{Date: date, Count: counts[date]})
	}
	return report, nil
}

// FormatMarkdown formats the digest into standup markdown
func FormatMarkdown(report DigestReport) string {
	var sb strings.Builder
	dateStr := report.Generated.Format("2006-01-02")
	sb.WriteString(fmt.Sprintf("## Standup — %s\n\n", dateStr))

	var completed, decisions []ActivityItem
	for _, item := range report.Items {
		if item.Kind == "task" || item.Kind == "capture" {
			completed = append(completed, item)
		} else if item.Kind == "decision" {
			decisions = append(decisions, item)
		}
	}

	if len(completed) > 0 {
		sb.WriteString("### ✅ Completed\n")
		for _, item := range completed {
			proj := ""
			if item.Project != "" && item.Project != report.Project {
				proj = fmt.Sprintf(" (%s)", item.Project)
			}
			if item.Kind == "task" {
				sb.WriteString(fmt.Sprintf("- Task done: %s%s\n", item.Summary, proj))
			} else {
				sb.WriteString(fmt.Sprintf("- %s%s\n", item.Summary, proj))
			}
		}
		sb.WriteString("\n")
	}

	if len(decisions) > 0 {
		sb.WriteString("### 🏗️ Decisions\n")
		for _, item := range decisions {
			proj := ""
			if item.Project != "" && item.Project != report.Project {
				proj = fmt.Sprintf(" (%s)", item.Project)
			}
			sb.WriteString(fmt.Sprintf("- ADR: %s%s\n", item.Summary, proj))
		}
		sb.WriteString("\n")
	}

	if report.CurrentTask != "" {
		sb.WriteString("### ⚡ Currently Working On\n")
		lines := strings.Split(report.CurrentTask, "\n")
		for _, l := range lines {
			if strings.TrimSpace(l) != "" {
				if strings.HasPrefix(l, "- ") {
					sb.WriteString(l + "\n")
				} else {
					sb.WriteString("- " + l + "\n")
				}
			}
		}
		sb.WriteString("\n")
	}

	sb.WriteString("---\n*Generated by Herdr Logbook*\n")
	return sb.String()
}

// calculateStreak counts consecutive days with activity ending today. An empty
// today does not break a streak that is still alive yesterday.
func calculateStreak(counts map[string]int, now time.Time) int {
	streak := 0
	// A streak can never be longer than the number of days that saw activity.
	for i := 0; i <= len(counts); i++ {
		if counts[now.AddDate(0, 0, -i).Format("2006-01-02")] > 0 {
			streak++
		} else if i > 0 {
			break
		}
	}
	return streak
}

func markdownFiles(dir string) []string {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil
	}
	var paths []string
	for _, entry := range entries {
		if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".md") {
			paths = append(paths, filepath.Join(dir, entry.Name()))
		}
	}
	return paths
}

// parseInboxFile reads a monthly inbox file written by internal/capture: each
// entry is a "## <timestamp>[ — metadata]" heading followed by the note body.
func parseInboxFile(path, projectName string) []ActivityItem {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}

	var items []ActivityItem
	var current *ActivityItem
	flush := func() {
		if current != nil {
			if current.Summary == "" {
				current.Summary = "(empty entry)"
			}
			items = append(items, *current)
			current = nil
		}
	}

	for _, line := range strings.Split(string(data), "\n") {
		if heading, ok := strings.CutPrefix(line, "## "); ok {
			flush()
			// "## 2026-07-30 14:20 — Branch: `main`" — drop the metadata suffix.
			if idx := strings.Index(heading, " —"); idx >= 0 {
				heading = heading[:idx]
			}
			parsed, err := time.ParseInLocation("2006-01-02 15:04", strings.TrimSpace(heading), time.Local)
			if err != nil {
				continue
			}
			current = &ActivityItem{Time: parsed, Project: projectName, Kind: "capture"}
			continue
		}
		// The summary is the first real line of the body; everything after it
		// only matters for the note itself.
		if current == nil || current.Summary != "" {
			continue
		}
		body := strings.TrimSpace(line)
		// Skip the metadata list and the fence a terminal capture opens with.
		if body == "" || strings.HasPrefix(body, "- Branch:") || strings.HasPrefix(body, "- Source:") || strings.HasPrefix(body, "``") {
			continue
		}
		body = strings.TrimPrefix(body, "- ")
		if task, ok := strings.CutPrefix(body, "Task done: "); ok {
			current.Kind = "task"
			current.Summary = task
		} else {
			current.Summary = body
		}
	}
	flush()
	return items
}

func parseDecisionFile(path, projectName string) (ActivityItem, bool) {
	data, err := os.ReadFile(path)
	if err != nil {
		return ActivityItem{}, false
	}

	var title, dateStr string
	for _, line := range strings.Split(string(data), "\n") {
		if strings.HasPrefix(line, "# Decision: ") {
			title = strings.TrimPrefix(line, "# Decision: ")
		} else if strings.HasPrefix(line, "- Date: ") {
			dateStr = strings.TrimSpace(strings.TrimPrefix(line, "- Date: "))
		}
	}

	if title != "" && dateStr != "" {
		if t, err := time.ParseInLocation("2006-01-02", dateStr, time.Local); err == nil {
			return ActivityItem{
				Time:    t,
				Summary: title,
				Project: projectName,
				Kind:    "decision",
			}, true
		}
	}
	return ActivityItem{}, false
}

func parseNowFile(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		return ""
	}

	inTask := false
	var taskBody []string
	for _, line := range strings.Split(string(data), "\n") {
		if strings.HasPrefix(line, "## Current task") {
			inTask = true
			continue
		} else if inTask && strings.HasPrefix(line, "## ") {
			break
		}
		if inTask {
			taskBody = append(taskBody, line)
		}
	}
	return strings.TrimSpace(strings.Join(taskBody, "\n"))
}
